### ISSUE TITLE
Classes with the same name clash

### ISSUE THREAD

**Issue by fourst4r** [SomeRanDev/reflaxe.CPP#29]
Classes with the same name but different packages will clash and only one of the classes will be compiled.

For example:
```haxe
// foo/Baz.hx
package foo;
class Baz { public function new() {} }
```
```haxe
// bar/Baz.hx
package bar;
class Baz { public function new() {} }
```
```haxe
// Main.hx
package;
function main() {
    new foo.Baz();
    new bar.Baz();
}
```

This will generate a `foo_Baz.cpp` but there is no `bar_Baz.cpp` generated.

**Comment by RobertBorghese** [comment]
Yiiiikes, wtf. Okay, I'll try and check this out asap. Sorry for delay as always 😰

**Comment by SomeRanDev** [comment]
Should be fixed with Reflaxe update! https://github.com/SomeRanDev/reflaxe/commit/5faaa5f3c747323b6eb6d9c086cbb251dea50cd9
