### ISSUE TITLE
@:include does not gen #include for Main.h/Main.cpp

### ISSUE THREAD

**Issue by maihd** [SomeRanDev/reflaxe.CPP#39]
@:include does not gen #include for Main.h/Main.cpp, instead of that, it will generate #include for _main_.cpp.

Screenshots from my current project:
![image](https://github.com/SomeRanDev/reflaxe.CPP/assets/7189568/d87c0bca-8cc5-472e-8523-424546e94612)
![image](https://github.com/SomeRanDev/reflaxe.CPP/assets/7189568/14eda81e-0b0a-48b0-88e5-b8fa71465ce4)
![image](https://github.com/SomeRanDev/reflaxe.CPP/assets/7189568/fb9e631d-8759-4d54-b019-4d683393f760)

**Comment by SomeRanDev** [comment]
Hello! Thanks for the report! 

`@:include` will add includes to the file the type is used in. If you wish to add an include to the file the class is generated in, you want to use `@:headerInclude` or `@:cppInclude`.

Hope this helps!

**Comment by SomeRanDev** [comment]
For example, you'd want to add `@:include("Application.h")` to your `extern class Application` so that whenever that extern class is used, that file is included.

**Comment by maihd** [comment]
Worked! Tks

**Comment by maihd** [comment]
Additional, after read https://all-things-andy-gavin.com/2011/03/12/making-crash-bandicoot-gool-part-9/, find out Reflaxe.CPP can be using like this approach, which proofed have advantages 2 decades ago:)

**Comment by SomeRanDev** [comment]
Cool, thank you for using! Sorry since Reflaxe/C++ has some missing features, but I hope you are able to find things working to your liking! 😁
