### ISSUE TITLE
The path to `std` is not found on the M1 when compiling

### ISSUE THREAD

**Issue by Just-Feeshy** [SomeRanDev/reflaxe.CPP#43]
I'm still new to this library, and I instantly got this error when I followed the example.

```
/Users/diegofonseca/Haxe/reflaxe,cpp/git/src/cxxcompiler/subcompilers/Types.hx:231: characters 10-22 : Type not found : cxx.Compiler
/Users/diegofonseca/Haxe/reflaxe,cpp/git/src/cxxcompiler/subcompilers/Types.hx:229: lines 229-246 : Void should be Null<String>
/Users/diegofonseca/Haxe/reflaxe,cpp/git/src/cxxcompiler/subcompilers/Expressions.hx:838: characters 16-28 : Type not found : cxx.Compiler
/Users/diegofonseca/Haxe/reflaxe,cpp/git/src/cxxcompiler/subcompilers/Expressions.hx:412: characters 35-47 : Type not found : cxx.Compiler
/Users/diegofonseca/Haxe/reflaxe,cpp/git/src/cxxcompiler/Compiler.hx:840: charac
ters 15-27 : Type not found : cxx.Compiler
/Users/diegofonseca/Haxe/reflaxe,cpp/git/src/cxxcompiler/Compiler.hx:862: characters 6-15 : Type not found : cxx.CMake
```

**Comment by SomeRanDev** [comment]
Huh... that is interesting. I don't have a Mac, so it'll be hard to test, but I'll poke around and see if I can figure it out.

**Comment by Just-Feeshy** [comment]
How does reflaxe work when it comes to including directories?

**Comment by SomeRanDev** [comment]
Ohhh, did you follow the [installation instructions](https://github.com/SomeRanDev/reflaxe.CPP?tab=readme-ov-file#nightly-installation)? You need to haxelib git from nightly.

**Comment by SomeRanDev** [comment]
Main and nightly are the same code. But since `haxelib` doesn't allow multiple source directories, they need to be merged together before being used as a library. So `nightly` is just `main` but packaged to be used properly.

**Comment by Just-Feeshy** [comment]
Ohh, that makes a lot more sense, thank you
